changelog:
  exclude:
    authors:
      - github-actions[bot]
    labels:
      - ignore-for-release
  categories:
    - title: evo-sdk
      labels:
        - evo-sdk
    - title: evo-sdk-common
      labels:
        - evo-sdk-common
    - title: evo-files
      labels:
        - evo-files
    - title: evo-objects
      labels:
        - evo-objects
    - title: Breaking Changes 🛠
      labels:
        - semver-major
        - breaking-change
    - title: Other Changes
      labels:
        - "*"
