# generated by datamodel-codegen:
#   filename:  spec.yaml

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, Field, StrictInt, StrictStr

from .._model_config import CustomBaseModel


class ListFileLinks(CustomBaseModel):
    self: StrictStr = Field(..., title="Self")


class ListFilesResponseLinks(CustomBaseModel):
    next: StrictStr | None = Field(None, title="Next")
    prev: StrictStr | None = Field(None, title="Prev")
    self: StrictStr = Field(..., title="Self")


class UploadFileResponse(CustomBaseModel):
    """
    Upload file response
    """

    file_id: UUID = Field(..., title="File Id")
    upload: StrictStr = Field(..., title="Upload")
    version_id: StrictStr = Field(..., title="Version Id")


class UserInfo(CustomBaseModel):
    email: StrictStr | None = Field(None, examples=["kim@example.test"], title="Email Address")
    """
    The primary email address of the user. Can be null if an error occurred while retrieving this information.
    """
    id: UUID = Field(..., examples=["59b73891-5538-4e45-ae67-f8c5b00d7405"], title="User ID")
    """
    The ID of the user
    """
    name: StrictStr | None = Field(None, examples=["Kim Kim"], title="Full Name")
    """
    The full name of the user. Can be null if an error occurred while retrieving this information.
    """


class FileVersionResponse(CustomBaseModel):
    """
    Metadata for specific file version
    """

    created_at: AwareDatetime = Field(..., title="Created At")
    created_by: UserInfo | None = None
    file_id: UUID = Field(..., title="File Id")
    link: StrictStr = Field(..., title="Link")
    name: StrictStr = Field(..., title="Name")
    path: StrictStr = Field(..., title="Path")
    size: StrictInt = Field(..., title="Size")
    version_id: StrictStr = Field(..., title="Version Id")


class ListFile(CustomBaseModel):
    created_at: AwareDatetime = Field(..., title="Created At")
    created_by: UserInfo | None = None
    etag: StrictStr = Field(..., title="Etag")
    file_id: UUID = Field(..., title="File Id")
    links: ListFileLinks
    name: StrictStr = Field(..., title="Name")
    path: StrictStr = Field(..., title="Path")
    size: StrictInt = Field(..., title="Size")
    version_id: StrictStr = Field(..., title="Version Id")


class ListFilesResponse(CustomBaseModel):
    """
    List files.
    """

    count: StrictInt = Field(..., title="Count")
    files: list[ListFile] = Field(..., title="Files")
    limit: StrictInt = Field(..., title="Limit")
    links: ListFilesResponseLinks
    offset: StrictInt = Field(..., title="Offset")
    total: StrictInt = Field(..., title="Total")


class DownloadFileResponse(CustomBaseModel):
    """
    Download file response.
    """

    created_at: AwareDatetime = Field(..., title="Created At")
    created_by: UserInfo | None = None
    download: StrictStr = Field(..., title="Download")
    etag: StrictStr = Field(..., title="Etag")
    file_id: UUID = Field(..., title="File Id")
    name: StrictStr = Field(..., title="Name")
    path: StrictStr = Field(..., title="Path")
    self: StrictStr = Field(..., title="Self")
    size: StrictInt = Field(..., title="Size")
    version_id: StrictStr = Field(..., title="Version Id")
    versions: list[FileVersionResponse] | None = Field(None, title="Versions")
