"""
Workspaces API
=============

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

This code is generated from the OpenAPI specification for Workspaces API.
API version: 1.0
"""

# Import endpoint apis.
from .api import DefaultApi

__all__ = [
    "DefaultApi",
]
